name: car_identifier_app
description: "A new Flutter project."
publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.8.1
dependencies:
  flutter:
    sdk: flutter
  isar: ^3.1.0
  isar_flutter_libs: ^3.1.0
  flutter_riverpod: ^2.4.0
  path_provider: ^2.0.0
  image_picker: ^1.0.7
  flutter_dotenv: ^5.1.0
  http: ^1.2.0
  url_launcher: ^6.3.0

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.0
  isar_generator: ^3.1.0

  flutter_lints: ^5.0.0


flutter:
  assets:
    - assets/data/cars.json
    - assets/logos/
    - .env
  uses-material-design: true
